import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ully</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <main>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
        <h1>ully</h1>
      </main>
    </>
  )
}
