import Head from 'next/head'

import { HiOutlinePencilAlt } from 'react-icons/hi'
import { StitcheWrapper } from '@/styles/wrapper.stitche'

import Input from '@/components/input/Input.module'
import Button from '@/components/button/Button.module'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <StitcheWrapper>
        {/* <Button title='wala' /> */}
        <Input label='test' />
      </StitcheWrapper>
    </>
  )
}
