name: Next.js

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  nextjs-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        working-directory: ./vercel
        run: npm install
      - name: Run tests
        working-directory: ./vercel
        run: npm run test
